### ISSUE TITLE
Compound index support

### ISSUE THREAD

**Issue by HiroshiHorie** [tekartik/idb_sqflite#1]
Hello, first of all, thanks for the hard work for your packages.
I'm currently implementing your idb_sqflite as an embedded db for my mobile app, (which will later be ported for web also so I need idb).

I ran into a few problems:

1. Since your code unfortunately doesn't support compound indexes, how would I implement the following simple use case:

I have a store of messages (id, userId, createdAt, .....) and I want to query only userId = X and sort by createdAt at the same time.
This would be easy with a compound index.

The workaround I can think of are the following:
- Create a store for every userId
- Create indexes for every userIds (which doesn't scale)
These workarounds are ugly and I am hoping to avoid. Are there any ways to achieve this with the current idb_sqflite implementation ?

2. How to encrypt / decrypt the reads and writes.
I would like to have a simple encryption mechanism since the sqflite dbs are easily readable.
Since idb put accepts an object, I would need to iterate and encrypt all values separately, which is not ideal. It would be best if there is a callback function or filter at each JSON serialize/deserialize.

Regards

**Comment by alextekartik** [comment]
> Since your code unfortunately doesn't support compound indexes

Actually compound indecies are supported and you should be able to create such index:

```
var index = store.createIndex('my_compound_index', ['userId', 'createAt']);
```

as defined in the indexedDB documentation https://developer.mozilla.org/en-US/docs/Web/API/IDBObjectStore/createIndex

You should be able to use the proper KeyRange to filter by userId and sort by createdAt with openCursor. This should match your needs.

> How to encrypt / decrypt the reads and writes

On this a different topic, I need to think more (and maybe start a different issue to follow on it). The goal was to provide the indexedDB API as is to have the same behavior on Web and Mobile. IndexedDB does not have such feature so you will have this security issue on the Web at some point.
Yes the idea of a codec (like it exists in [sembast](https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/codec.md) - which is exactly what you propose) to encode/decode the object could be a reasonable solution. This would not work on the Web though (index would not work then) so it could be a idb_sqflite only solution.

Alternatively I'm thinking of building another database system on top of idb and sqflite that could allow such thing. Currently sembast is one portable solution (sembast_web/sembast_sqflite) but it has the drawback of loading everything in memory (but I know users with 10K records without issues)

**Comment by HiroshiHorie** [comment]
> Actually compound indecies are supported and you should be able to create such index:

I tried again and now it works!
It was crashing when I tried it so I assumed there was no compound index support.
Unfortunately I didn't keep error message. Maybe it just simply needed to re-create the db.

> > How to encrypt / decrypt the reads and writes
> This would not work on the Web though (index would not work then) so it could be a idb_sqflite 

You are right, idb web wouldn't work obviously. In my case of using idb I better encrypt sensitive values of the object separately. Since idb web is also easy to salvage the data from browser debug tools.

> Alternatively I'm thinking of building another database system on top of idb and sqflite that could allow such thing. Currently sembast is one portable solution (sembast_web/sembast_sqflite) but it has the drawback of loading everything in memory (but I know users with 10K records without issues)

I haven't tried sambast, but I'm slightly worried that everything resides in the memory. Since I designed my app to sync with my server, it is possible the local db will grow large.

For my use case I will continue to use idb_sqflite which matches well my use case, but one slight concern is that if it will be maintained long term.

Anyways this was my work around for my problem, combining 2 values in to 1 integer so key range and sort is possible. but there is no need since compound index is supported.

**This code is not required since compound index is supported**
```
  enum IndexMode {
    value,
    upper,
    lower,
  }
  
   num calcIndex({
    @required String userId,
    DateTime dateTime,
    indexMode = IndexMode.value,
  }) {
    assert(userId != null);

    var value = 0;
    if (indexMode == IndexMode.lower) value = 0;
    if (indexMode == IndexMode.upper) value = 0xFFFFFFFF;
    if (indexMode == IndexMode.value) value = dateTime.millisecondsSinceEpoch;

    final data = ByteData(8);
    data.setUint32(0, userId.hashCode);
    data.setUint32(4, value);
    return data.getInt64(0); // Float on web ?
  }
```
