### ISSUE TITLE
Error: Getter not found: 'idbFactorySqflite'

### ISSUE THREAD

**Issue by h4xhor** [tekartik/idb_sqflite#3]
Hi alextekartik,

Thanks for your kindness in open sourcing your package.

I'm trying to use it for Flutter and was following the example.

On this line
```
var factory = idbFactorySqflite;
```
I get this error:
```
Error: Getter not found: 'idbFactorySqflite'.                                                                                                   
  var factory = idbFactorySqflite;
                ^^^^^^^^^^^^^^^^^
```
I thought it was maybe because I was doing something wrong in Flutter, so I tried it on a dart console application using [stagehand](https://dart.dev/tutorials/server/get-started) and also get the same error.

Then I saw this in your idb_sqflite/CHANGELOG.md
```
 11 ## 0.2.0
 12 
 13 * deprecate idbFactorySqflite to allow non-flutter support in the future
```
So maybe it's deprecated. May you please confirm for me? Many thanks.

**Comment by alextekartik** [comment]
Thanks for the report. Indeed before the package was flutter only and now it can work on VM using sqflite_ffi so it has to change to this weird declaration:

```dart
import 'package:idb_sqflite/idb_sqflite.dart';
import 'package:sqflite/sqflite.dart';

void main() {
    // Flutter default factory
    var idbFactorySqflite = getIdbFactorySqflite(databaseFactory);
  });
}
```

It is kind of weird since the factory needs a sqflite database factory...sorry! I have update the doc. Thanks!

**Comment by h4xhor** [comment]
Hi alextekartik, it works on Flutter. Many thanks for your kind help!
