### ISSUE TITLE
Does package support isolates?

### ISSUE THREAD

**Issue by jayjah** [tekartik/idb_sqflite#4]
Actually your project is quite interesting, but one questions stands open after I read the readme. Does this package support isolates? So is it possible to use this package in a quite multithreading environment?

**Comment by alextekartik** [comment]
Unfortunately, sqflite itself is not cross isolate safe (however all queries will run in a separate thread). If we could setup easily cross-isolate mutex around sqflite queries, it would be cross isolate safe but I'm not aware of any lightweight solution for this.
